
-- non-encrypted password: jwtpass
INSERT INTO USER (id, password, username) VALUES (1, '$2a$10$qtH0F1m488673KwgAfFXEOWxsoZSeHqqlB/8BTt3a6gsI5c2mdlfe', 'admin');

INSERT INTO TRANSACTION (id, merchantId, acquirerId,paymentMethod,status,errorCode) VALUES (1, 1, 2, 'CREDIT_CARD','WAITING','NONE');
INSERT INTO TRANSACTION (id, merchantId, acquirerId,paymentMethod,status,errorCode) VALUES (2, 2, 1, 'MISTERCASH','APPROVED','NONE');

INSERT INTO CUSTOMER(customerInfo_id,customerInfocreated_at,customerInfoupdated_at,customerInfodeleted_at,customerInfonumber,customerInfoexpiryMonth,customerInfoexpiryYear,customerInfostartMonth,customerInfostartYear,customerInfoissueNumber,customerInfoemail,customerInfobirthday,customerInfogender,customerInfobillingTitle,customerInfoAuthorization,billingFirstName,billingLastName,billingCompany,billingAddress1,billingAddress2,billingCity,billingPostcode,billingState,billingCountry,billingPhone,billingFax,shippingTitle,shippingFirstName,shippingLastName,shippingCompany,shippingAddress1,shippingAddress2,shippingCity,shippingPostcode,shippingState,shippingCountry,shippingPhone,shippingFax) VALUES (1,'2015-10-09 12:09:10','2015-10-09 12:09:10',NULL,'401288XXXXXX1881',6,2017,NULL,NULL,NULL,'aydinbg@gmail.com','1986-03-20 12:09:10',NULL,NULL,'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXJjaGFudFVzZXJJ ZCI6MSwicm9sZSI6ImFkbWluIiwibWVyY2hhbnRJZCI6MSwic3ViTWVyY hhbnRJZHMiOltdLCJ0aW1lc3RhbXAiOjE0NDQzODk4ODB9.zPxVu4fk y1uG2fO3X2RbxiI4otK_HG7M4MMTB298','Aydin','Gungordu',NULL,'test address',NULL,'Antalya',07070,NULL,'TR',NULL,NULL,NULL,'Aydin','Gungordu',NULL,'test address',NULL,'Antalya',07070,NULL,'TR',NULL,NULL);
INSERT INTO CUSTOMER(customerInfo_id,customerInfocreated_at,customerInfoupdated_at,customerInfodeleted_at,customerInfonumber,customerInfoexpiryMonth,customerInfoexpiryYear,customerInfostartMonth,customerInfostartYear,customerInfoissueNumber,customerInfoemail,customerInfobirthday,customerInfogender,customerInfobillingTitle,customerInfoAuthorization,billingFirstName,billingLastName,billingCompany,billingAddress1,billingAddress2,billingCity,billingPostcode,billingState,billingCountry,billingPhone,billingFax,shippingTitle,shippingFirstName,shippingLastName,shippingCompany,shippingAddress1,shippingAddress2,shippingCity,shippingPostcode,shippingState,shippingCountry,shippingPhone,shippingFax) VALUES (2,'2015-10-09 12:09:10','2015-10-09 12:09:10',NULL,'401288XXXXXX1881',6,2017,NULL,NULL,NULL,'michael@gmail.com','1986-03-20 12:09:10',NULL,NULL,'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXJjaGFudFVzZXJJ ZCI6MSwicm9sZSI6ImFkbWluIiwibWVyY2hhbnRJZCI6MSwic3ViTWVyY hhbnRJZHMiOltdLCJ0aW1lc3RhbXAiOjE0NDQzODk4ODB9.zPxVu4fk y1uG2fO3X2RbxiI4otK_HG7M4MMTB298','Michael','Kara',NULL,'test address',NULL,'Antalya',07070,NULL,'TR',NULL,NULL,NULL,'Michael','Kara',NULL,'test address',NULL,'Antalya',07070,NULL,'TR',NULL,NULL);
